apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: {{ .Values.postgres.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.pvc.storageClassName }}
  hostPath:
    path: "/mnt/data"
